version: '3.8'
services:
  web:
    build: .
    command: gunicorn trafficwatch.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq

  celery:
    build: .
    command: celery -A trafficwatch worker -l info
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq

  celery-beat:
    build: .
    command: celery -A trafficwatch beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - web
      - rabbitmq

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # Management interface
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
