# Generated by Django 5.0.6 on 2024-05-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficCamera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("camera_id", models.CharField(max_length=20, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("image_url", models.URLField()),
                ("timestamp", models.DateTimeField()),
                ("image_height", models.IntegerField()),
                ("image_width", models.IntegerField()),
                ("image_md5", models.CharField(max_length=32)),
            ],
        ),
    ]
